# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: PoolManager
    address:
    - '0x000000000004444c5dc75cB358380D2e3dE08A90'
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 indexed id, uint256 amount)
    - event: Donate(bytes32 indexed id, address indexed sender, uint256 amount0, uint256 amount1)
    - event: Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, uint24 fee, int24 tickSpacing, address hooks, uint160 sqrtPriceX96, int24 tick)
    - event: ModifyLiquidity(bytes32 indexed id, address indexed sender, int24 tickLower, int24 tickUpper, int256 liquidityDelta, bytes32 salt)
    - event: OperatorSet(address indexed owner, address indexed operator, bool approved)
    - event: OwnershipTransferred(address indexed user, address indexed newOwner)
    - event: ProtocolFeeControllerUpdated(address indexed protocolFeeController)
    - event: ProtocolFeeUpdated(bytes32 indexed id, uint24 protocolFee)
    - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee)
    - event: Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount)
unordered_multichain_mode: true
preload_handlers: true
